export const FILES_PROCESSING_CONSTANTS = {
  UPLOAD_FILE_USE_CASE: 'UPLOAD_FILE_USE_CASE',
  FILE_UPLOADED_PRODUCER: 'FILE_UPLOADED_PRODUCER',
  GET_FILE_STREAM: 'GET_FILE_STREAM',
  PROCESS_STREAM_FILE: 'PROCESS_STREAM_FILE',
  RABBIT_PRODUCER: 'RABBIT_PRODUCER',
};
